apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-app
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  source:
    repoURL: https://github.com/mytreya-rh/external-secrets-gitops
    path: manifests
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

