apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: bitwarden-tls-certs
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.14.0"
    app.kubernetes.io/managed-by: external-secrets-operator
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
    - external-secrets-bitwarden-sdk-server.external-secrets.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: my-issuer
  duration: "8760h"