apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: metrics-serving-cert
  creationTimestamp: null
  labels:
    app: external-secrets-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: external-secrets-operator
    control-plane: controller-manager
    svc: external-secrets-operator-controller-manager-metrics-service
  name: external-secrets-operator-controller-manager-metrics-service
spec:
  ports:
  - name: metrics-https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: metrics-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: external-secrets-operator
status:
  loadBalancer: {}
