apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: external-secrets-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: external-secrets-operator
    control-plane: controller-manager
  name: external-secrets-operator-externalsecrets-editor-role
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - externalsecrets/status
  verbs:
  - get
