apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: external-secrets-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: external-secrets-operator
    control-plane: controller-manager
  name: external-secrets-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services/metrics
  verbs:
  - get
