apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: external-secrets-operator
    config.openshift.io/inject-trusted-cabundle: "true"
    control-plane: controller-manager
  name: external-secrets-operator-trusted-ca-bundle
