apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: external-secrets-operator
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
  namespace: external-secrets-operator
spec:
  endpoints:
    - honorLabels: false
      interval: 60s
      path: /metrics
      scheme: https
      scrapeTimeout: 30s
      targetPort: 8443
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        ca:
          configMap:
            name: openshift-service-ca.crt
            key: service-ca.crt
        serverName: external-secrets-operator-controller-manager-metrics-service.external-secrets-operator.svc.cluster.local
  selector:
    matchLabels:
      control-plane: controller-manager