apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: external-secrets-operator
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/managed-by: kustomize
    control-plane: controller-manager
  name: metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - "services/metrics"
  verbs:
  - get
