apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: external-secrets-operator
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/managed-by: kustomize
    control-plane: controller-manager
  name: controller-manager
  namespace: system
