apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secretstore  # ! Replace with a unique name for your ClusterSecretStore.
  annotations:
    external-secrets.io/example: "true"
spec:
  provider:
    gcpsm:
      projectID: openshift-sample-project  # ! Replace with your GCP project ID.
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-creds  # ! Replace with the name of the Kubernetes Secret containing your GCP credentials.
            key: secret-access-key.json  # ! Replace with the key in the Secret that holds the GCP service account JSON.
            namespace: external-secrets  # ! Replace with the namespace where the above Secret is located.
