apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  labels:
    app: external-secrets-operator
  name: gcp-secret  # ! Name of the ExternalSecret resource in your cluster.
  namespace: external-secrets  # ! Replace with the namespace where this ExternalSecret should be created.
  annotations:
    external-secrets.io/example: "true"
spec:
  refreshInterval: 1h  # ! How often to sync the secret from the external provider.
  secretStoreRef:
    name: secretstore  # ! Replace with the name of your SecretStore or ClusterSecretStore.
    kind: SecretStore  # ! Use 'ClusterSecretStore' if referring to a cluster-wide store.
  target:
    name: k8s-secret  # ! Name of the resulting Kubernetes Secret.
    creationPolicy: Owner  # ! Determines if the secret should be created ('Owner'), adopted, or left unchanged.
  data:
    - secretKey: Key  # ! Key name inside the Kubernetes Secret.
      remoteRef:
        key: gcp-secret  # ! Name of the secret in GCP Secret Manager.
        property: Key
