apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: secret-cluster  # ! Name of the ClusterExternalSecret resource.
  annotations:
    external-secrets.io/example: "true"
spec:
  namespaceSelector:
    matchLabels:
      app.kubernetes.io/managed-by: external-secrets-operator  # ! Label used to select target namespaces. Adjust as needed.
  externalSecretSpec:
    refreshInterval: 1h  # ! Frequency to sync secrets from the external provider.
    secretStoreRef:
      name: gcp-cluster-secretstore  # ! Name of the ClusterSecretStore to use.
      kind: ClusterSecretStore
    target:
      name: gcp-secret-k8s  # ! Name of the resulting Kubernetes Secret in each selected namespace.
      creationPolicy: Owner  # ! Policy for creating/adopting the Kubernetes Secret.
    data:
      - secretKey: key  # ! Key name inside the resulting Kubernetes Secret.
        remoteRef:
          key: gcp-secret  # ! Name of the secret in GCP Secret Manager.
