apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  labels:
    app: external-secrets-operator
  name: password-sample
  namespace: external-secrets  # ! Replace with the namespace where the generator should be created.
  annotations:
    external-secrets.io/example: "true"
spec:
  length: 20  # ! Desired length of the generated password.
  includeSymbols: true  # ! Set to true to include symbols (e.g., !, @, #).
  excludeUppercase: false  # ! Set to true to exclude uppercase letters.
  excludeLowercase: false  # ! Set to true to exclude lowercase letters.
  excludeNumbers: false  # ! Set to true to exclude numeric characters.
