apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore
  namespace: external-secrets    # ! Replace this with your preferred namespace name.
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    gcpsm:
      projectID: openshift-sample-project  # ! Replace this with your GCP project ID.
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-creds             # ! Replace with the name of the Kubernetes secret that contains your GCP credentials.
            key: secret-access-key.json # ! Replace with the key inside the secret that holds the GCP service account JSON.
