---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.14.3"
    app.kubernetes.io/managed-by: external-secrets-operator
    external-secrets.io/component: webhook
spec:
  commonName: external-secrets-webhook
  dnsNames:
    - external-secrets-webhook
    - external-secrets-webhook.external-secrets
    - external-secrets-webhook.external-secrets.svc
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: my-issuer
  duration: "8760h"
  secretName: external-secrets-webhook
