---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-edit
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.14.3"
    app.kubernetes.io/managed-by: external-secrets-operator
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - "external-secrets.io"
    resources:
      - "externalsecrets"
      - "secretstores"
      - "clustersecretstores"
      - "pushsecrets"
    verbs:
      - "create"
      - "delete"
      - "deletecollection"
      - "patch"
      - "update"
  - apiGroups:
      - "generators.external-secrets.io"
    resources:
      - "acraccesstokens"
      - "clustergenerators"
      - "ecrauthorizationtokens"
      - "fakes"
      - "gcraccesstokens"
      - "githubaccesstokens"
      - "quayaccesstokens"
      - "passwords"
      - "vaultdynamicsecrets"
      - "webhooks"
      - "grafanas"
      - "generatorstates"
    verbs:
      - "create"
      - "delete"
      - "deletecollection"
      - "patch"
      - "update"
